version: "3"
services:
  v2ray:
    image: ghcr.io/getimages/v2ray:latest
    container_name: v2ray_upstream
    restart: always
    command: [ "v2ray", "-config=/etc/v2ray/config.json" ]
    ports:
      - ${VMESS_PORT:-1013}:1013
    volumes:
      - ./config/:/etc/v2ray/
      - ./logs:/var/log/v2ray/
